FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN chmod +x entrypoint.sh

RUN apt-get update && apt-get install -y \
    ffmpeg libsm6 libxext6 libgl1-mesa-glx curl build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && \
    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

RUN pip install --extra-index-url https://python.openfilter.io/simple ".[dev]"

EXPOSE 8000

ENTRYPOINT [ "/app/entrypoint.sh" ]