services:
   ocr-app:
    image: openfilter-ocr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"       
    volumes:
      - ./output:/app/output      
      - ./hello.mov:/app/hello.mov  

    environment:
      - DOCKER_SCAN_SUGGEST=false